/** Sheet/range protection. */
function protectDashboardSheets() {
  var cfg = getConfig();
  var ss = openDashboardSpreadsheet_();
  var admins = cfg.ADMIN_EMAILS.length ? cfg.ADMIN_EMAILS : [cfg.OWNER_EMAIL].filter(Boolean);

  protectSheetFully_(ss.getSheetByName(SHEETS.DASHBOARD), admins, 'Dashboard is generated by the system.');
  protectSheetFully_(ss.getSheetByName(SHEETS.CHARTS), admins, 'Charts are generated by the system.');
  protectReferenceSheet_(ss.getSheetByName(SHEETS.ADMIN_UNITS), admins);
  protectReferenceSheet_(ss.getSheetByName(SHEETS.ADMIN_SECTIONS), admins);
  protectReferenceSheet_(ss.getSheetByName(SHEETS.UNITS), admins);
  protectReferenceSheet_(ss.getSheetByName(SHEETS.SECTIONS), admins);
  protectRecordsSheet_(ss.getSheetByName(SHEETS.RECORDS), admins);
}

function protectSheetFully_(sheet, admins, description) {
  if (!sheet) return;
  removeProtections_(sheet);
  var protection = sheet.protect().setDescription(description || 'Protected by SQU Training System');
  applyProtectionEditors_(protection, admins);
}

function protectReferenceSheet_(sheet, admins) {
  if (!sheet) return;
  removeProtections_(sheet);
  var protection = sheet.protect().setDescription('Reference data protected. Edit only by admins.');
  applyProtectionEditors_(protection, admins);
}

function protectRecordsSheet_(sheet, admins) {
  if (!sheet) return;
  removeProtections_(sheet);
  var map = getHeaderMap_(sheet);
  var editableRanges = [];
  if (map[H.RECORD.NOTES]) editableRanges.push(sheet.getRange(2, map[H.RECORD.NOTES], Math.max(sheet.getMaxRows() - 1, 1), 1));
  if (map[H.RECORD.FINAL_STATUS]) editableRanges.push(sheet.getRange(2, map[H.RECORD.FINAL_STATUS], Math.max(sheet.getMaxRows() - 1, 1), 1));
  var protection = sheet.protect().setDescription('Records protected; only notes and final status are directly editable by admins.');
  if (editableRanges.length) protection.setUnprotectedRanges(editableRanges);
  applyProtectionEditors_(protection, admins);
}

function removeProtections_(sheet) {
  sheet.getProtections(SpreadsheetApp.ProtectionType.SHEET).forEach(function(p) {
    try { p.remove(); } catch (ignore) {}
  });
}

function applyProtectionEditors_(protection, admins) {
  try {
    protection.setWarningOnly(false);
    var editors = protection.getEditors();
    if (editors && editors.length) protection.removeEditors(editors);
    if (admins && admins.length) protection.addEditors(admins);
    if (protection.canDomainEdit()) protection.setDomainEdit(false);
  } catch (err) {
    logError_('applyProtectionEditors_', '', err);
  }
}
